### ISSUE TITLE
[BUG] webapp having parent DOM access due to no iframe sandbox

### ISSUE THREAD

**Issue by gafea** [tobychui/arozos#93] opened 2022-04-23 16:10 UTC
**Describe the bug**
A webapp can access and modify it's parent DOM elements from arozOS web interface due to missing restrictions with it's iframe sandbox attribute. This includes changing the look of arozOS's desktop or replacing innerHTML of other webapps for example.

Adding sandbox attribute to the webapp's iframe with limited allowance should fix the issue. [reference](https://www.w3schools.com/tags/att_iframe_sandbox.asp)

**To Reproduce**
1. Open the dummy webapp's index.html
2. Write the following line:
`<script>window.parent.document.getElementsByTagName('body')[0].innerHTML = 'destroyed';</script>`
3. Start the webapp

**Expected behavior**
webapp should be fully contained within their own iframe boxes and only be able to interact with the outer world using the API provided by the OS.

**Screen Recording**
https://user-images.githubusercontent.com/103837965/164913895-efc584b0-1c75-4ef8-98ad-b3243e102a2f.mp4

**Host Information(please complete the following information):**
 - OS: Windows 11
 - Arozos version v1.121

**Client Information(please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 99.0.1

**Comment by tobychui** [comment] 2022-04-24 02:39
By designs, webapps is able to access parent frames (and frames of other webapps) so that it makes interactions between windows easier. This might violate the standard way of implementing iframe on websites but it is necessary to do so on Web Desktop systems to enable functions like "on screen keyboards" and "virtual IMEs".

@yeungalan What do you think?

**Comment by tobychui** [comment] 2022-04-30 10:12
After internal discussion, we think that for any WebApps user installed, they should make sure the apps they install contains no virus or code that might damage their system. As quoted

> It is not Linux's job to stop you from shooting your foot. If you so choose to do so, then it is Linux's job to deliver Mr. Bullet to Mr. Foot in the most efficient way it knows.

For website shortcuts that launch as WebApp mode, due to CORS limtation, cross frame access will not be allowed at the browser level. So we will mark this issue as won't fix.

**Closed by tobychui** 2022-04-30 10:12 UTC
Labels: bug, wontfix
