### ISSUE TITLE
The iPhone safari browser cannot upload images

### ISSUE THREAD

**Issue by maoxiaotong** [tobychui/arozos#159] opened 2024-05-08 00:35 UTC
The iPhone safari browser does not respond to uploading pictures, but it can upload files

**Comment by maoxiaotong** [comment] 2024-05-09 03:28
> @maoxiaotong I don't have an iPhone, so there is nothing I can do. @yeungalan you got time to try reproduce this issue and let me know what is the issue?

iPhone all browsers, selected album pictures can not be uploaded, but on Android can be uploaded, so that iPhone users can not backup pictures, can improve this function

**Comment by tobychui** [comment] 2024-05-09 10:51
@maoxiaotong I have @yeungalan test it out for me with his iPhone (USA version). He told me that he cannot reproduce this bug you mentioned. You mind providing detail instruction (e.g. screen recording or steps to reproduce your issue) to show me how this bug occurs? Otherwise, there is nothing I can help and I will close this issue as "wont fix".

**Comment by tobychui** [comment] 2024-05-14 05:49
Unable to reproduce (assume particular iPhone / regional issues)

**Closed by tobychui** 2024-05-14 05:49 UTC
Labels: bug

**Comment by maoxiaotong** [comment] 2024-06-22 03:27
> Unable to reproduce (assume particular iPhone / regional issues)
The reason has been found, which is caused by the low version of IOS (IOS15). After upgrading to the latest IOS17.5.1, it can be uploaded normally
