### ISSUE TITLE
[BUG] Desktop Pop-up Window Not Disappear After Opening A Web App

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#73] opened 2021-08-23 07:56 UTC
**Describe the bug**
Right click on web desktop and then open file manager, the pop up window for desktop doesn't disappear.

**To Reproduce**
1. Go to Aroz OS desktop
2. Right click
3. Open File Manager

**Expected behavior**
You will see the desktop pop-up window will hover above the File Manager window.

**Screenshots**
![image](https://user-images.githubusercontent.com/69898202/130410679-29135491-e67d-4a8a-b773-761023aeb2f5.png)

**Host Information(please complete the following information):**
 - OS: Debian
 - Arozos version 

**Client Information(please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome

**Comment by tobychui** [comment] 2021-08-23 08:34
@yeungalan Could you try reproduce this bug on your Macbook? My guess will be the WebKit of @konykwong's Macbook is too old. If you cannot reproduce this issue on Big Sur, then we will label it as won't fix

**Comment by konykwong** [comment] 2021-08-23 08:46
This issue happens on Windows Chrome as well.

**Comment by tobychui** [comment] 2021-08-29 03:50
> 
> 
> This issue happens on Windows Chrome as well.

I can reproduce this issue on MacOS Chrome, however it is not reproducible on Windows Chrome. Are you sure your mouse right click button is working?

**Comment by tobychui** [comment] 2021-10-02 07:07
Fixed in v1.116, release pending.

**Closed by tobychui** 2021-10-02 07:07 UTC
Labels: bug
