### ISSUE TITLE
[BUG] Failed to construct 'WebSocket': The Url conains a fragment identifier

### ISSUE THREAD

**Issue by twinklestar03** [tobychui/arozos#91] opened 2022-04-17 18:12 UTC
**Describe the bug**
The upload will fail when upload a folder or a file which the filename contain '#' character.

**Expected behavior**
Should be able to upload things with # in filename.

**Host Information(please complete the following information):**
 - OS: Ubuntu 20.04
 - Go version: go version go1.16.7 linux/amd64
 - Arozos version: ArozOS development Revision 0.1.120

**Comment by yeungalan** [comment] 2022-04-17 19:48
Hi, may I know what browser you are using?

**Comment by tobychui** [comment] 2022-04-18 05:38
Hi @twinklestar03 ,

Thanks for raising this issue. This was caused by a missing encodeURIComponent in the upload endpoint generator. The bug has been fixed and will be pushed with the latest update in v1.121. 

![圖片](https://user-images.githubusercontent.com/24617523/163760242-59eab154-8e93-4271-ac2c-fa57f510a34e.png)

Thanks so much for your contribution!
(Issue will be closed after v1.121 release)

**Comment by twinklestar03** [comment] 2022-04-18 14:54
Thanks for the fast patch. 🥳

**Comment by tobychui** [comment] 2022-04-22 15:41
Patch has been released with v1.121

**Comment by twinklestar03** [comment] 2022-04-22 17:25
Sorry I have to re-open this issue, I think the patch is kinda broken.
After apply the latest version, whenever upload a filename contain a Chinese or Japanese characters, the filename won't be urldecoded.

**Comment by tobychui** [comment] 2022-04-24 02:27
Hi @twinklestar03,

I have try to apply a fix on commit #a42c4e2f4e3fbc675387299d620d673261bd1d78. You mind having a try on the latest source code and see if the problem still exists? Thanks!

**Comment by twinklestar03** [comment] 2022-04-24 13:47
I've apply the patch, now things work just fine.

**Closed** 2022-04-25 02:26 UTC
Labels: bug
