### ISSUE TITLE
[BUG] File Upload to Desktop stuck on Post Processing Stage

### ISSUE THREAD

**Issue by fred2088** [tobychui/arozos#87] opened 2022-02-02 15:06 UTC
**Describe the bug**

**To Reproduce**
1. Drap & Drop JPG/STL on web desktop
2. See error

**Expected behavior**

**Screenshots**

**Host Information(please complete the following information):**
 - OS: Win7 SP2
 - Go version go version go1.17.6 windows/amd64
 - Arozos version (e.g. 1.116)

**Client Information(please complete the following information):**
 - OS: Win7 same pc
 - Browser Chrome 
 - Version 版本 97.0.4692.99 (正式版本) (64 位元)
 - 
**Additional context**
![image](https://user-images.githubusercontent.com/8401029/152179836-bc2f6193-b83b-4076-9ac3-28000d872689.png)

**Comment by tobychui** [comment] 2022-02-03 03:15
A few of our co-authors has tried to reproduce your issue but failed. Can you try updating your ArozOS to v1.118 and see if the problem still exists? Or is there any error message produced in developer console or server terminal? Thanks!

**Comment by fred2088** [comment] 2022-02-03 07:10
just download and do a clean build on lastest 1.118, when drag & drop a jpg file onto the desktop got the same result
![image](https://user-images.githubusercontent.com/8401029/152297331-d109610b-9372-4882-8bd7-7de85f042691.png)

**Comment by tobychui** [comment] 2022-02-25 10:54
As non of our coauthors can reproduce this issue, we think this should be caused by the lack of delay on upload handler and the browser didn't catch the response fast enough on some specific environment / setups. We added a minimum upload delay of 100ms (aka if the upload time is < 100ms, the thread will sleep until 100ms) to the latest release. 

**This issue should be fixed in v1.119 now. If not, please request to re-open this issue.** 
Thanks for the issue report!

**Closed by tobychui** 2022-02-25 10:54 UTC
Labels: bug
